### ISSUE TITLE
Esercizio 2.16

### ISSUE THREAD

**Issue by FabioZTessitore** [daniele998/operazioni#2]
![es2_16](https://cloud.githubusercontent.com/assets/3002194/11845366/da3ec424-a413-11e5-8012-f6a7991cd622.jpg)

**Comment by FabioZTessitore** [comment]
per stampare il simbolo % devi scrivere %%

**Comment by FabioZTessitore** [comment]
ora manca la moltiplicazione

**Comment by daniele998** [comment]
fatto

**Comment by FabioZTessitore** [comment]
ma tu li provi i programmi prima di spedirli?

**Comment by daniele998** [comment]
si ma il modulo non riesco a farlo funzionare

**Comment by FabioZTessitore** [comment]
E allora perché rispondi che hai fatto?

Cmq il problema è il %
Quando scrivi %d va bene perché significa stampa un intero. Se invece vuoi
proprio stampare il carattere % devi scrivere %% (senza spazi)

Il mercoledì 16 dicembre 2015, daniele998 notifications@github.com ha
scritto:

**Comment by daniele998** [comment]
ora va l'ho provato

Il giorno 16 dicembre 2015 19:40, Fabio Z Tessitore <
notifications@github.com> ha scritto:
